### ISSUE TITLE
there is no prepare/ dir with download_glove.sh & download_t2m_evaluators.sh

### ISSUE THREAD

**Issue by zhange1990** [IDEA-Research/MotionCLR#1]
there is no prepare/ dir with download_glove.sh & download_t2m_evaluators.sh,
is there something missing?

**Comment by LinghaoChan** [comment]
Thanks for pointing out this. Fixed in 34bd8ff6a98e8b60583460aa23d42b126df89ccd.

**Comment by LinghaoChan** [comment]
I close the issue as no further discussions. Ok to open if any question.
