### ISSUE TITLE
关于npy转bvh

### ISSUE THREAD

**Issue by lz233-alt** [IDEA-Research/MotionCLR#3]
您好，您的工作我试用了感觉效果非常好，但是在实际使用时遇到问题，请问如何将生成的npy转为bvh，以及如何找到对应的模型骨骼。

**Comment by LinghaoChan** [comment]
> 您好，您的工作我试用了感觉效果非常好，但是在实际使用时遇到问题，请问如何将生成的npy转为bvh，以及如何找到对应的模型骨骼。

Thanks for your interest. We will make our results to bvh online soon.

**Comment by lz233-alt** [comment]
我尝试使用输出的joints_npy以及root_npy通过smpl2bvh的开源项目(https://github.com/KosukeFukazawa/smpl2bvh)进行转换，出来的骨骼是正确的，但是动作和姿态完全无法匹配上
![image](https://github.com/user-attachments/assets/365db1ea-aed5-417f-af33-a1f3d9d4eb31)

**Comment by lz233-alt** [comment]
我已经成功转为bvh，感谢您的回复

**Comment by LinghaoChan** [comment]
@lz233-alt Congrats! So amazing.
